# Generated by Django 6.1 on 2026-08-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
